const ja = {
  error: 'Lỗi',
  cancel: 'Huỷ',
  back: 'Trở Lại',
  errorNetwork: 'Lỗi Mạng. Xin Vui Lòng Thử Lại!',
  somethingWentWrong: 'Xin Vui Lòng Thử Lại!',
  datetimeFormat: {
    serverTimeStamp: 'yyyy-MM-dd hh:mm:ss Z',
    monthDate: 'MM/DD',
    hourMinute: 'HH:mm',
    dateTime: 'YYYY-MM-DD HH:mm',
    full: 'yyyy-MM-DDTHH:mm:ss.SSSZ',
    date: 'DD/MM/yyyy',
  },
  login: {
    phoneNumberLabel: 'Số điện thoại*',
    passwordLabel: 'Mật khẩu*',
    phoneNumber: 'Số Điện Thoại',
    password: 'Mật Khẩu',
    login: 'Đăng Nhập',
    loginFailedMessage: 'Sai số điện thoại hoặc mật khẩu',
    logoutFailedMessage: 'Đăng Xuất Thất Bại',
    hello: 'Xin chào,',
    notHaveAccount: 'Chưa có tài khoản?',
    register: 'Đăng ký',
    forgotPassword: 'Quên mật khẩu?',
  },
  loginWithSavedUser: {
    title: 'Đăng nhập',
    hello: 'Xin chào,',
    passwordPlaceholder: 'Nhập mật khẩu',
    forgetPassword: 'Quên mật khẩu?',
    changeAccount: 'Đổi tài khoản',
    errorPassword: 'Mật khẩu không chính xác.',
  },
  forgetPassword: {
    title: 'Quên mật khẩu',
    phoneNumberLabel: 'Số điện thoại*',
    phoneNumberPlaceholder: 'Nhập số điện thoại',
    selectAuthorizationMethod: 'Chọn phương thức mã xác thực*',
    byPhoneNumber: 'Qua số điện thoại',
    byEmail: 'Qua email đăng ký',
    send: 'Gửi',
  },
  register: {
    title: 'Đăng ký',
    haveAccount: 'Đã có tài khoản?',
    login: 'Đăng nhập',
    fullNameLabel: 'Họ tên*',
    fullNamePlaceholder: 'Nhập họ tên',
    phoneNumberLabel: 'Số điện thoại*',
    phoneNumberPlaceholder: 'Nhập số điện thoại',
    emailLabel: 'Email*',
    emailPlaceholder: 'Nhập email',
    passwordLabel: 'Mật khẩu*',
    passwordPlaceholder: 'Nhập mật khẩu',
    confirmPasswordLabel: 'Xác nhận mật khẩu*',
    confirmPasswordPlaceholder: 'Nhập lại mật khẩu',
    register: 'Đăng ký',
    confirmPasswordError: 'Xác nhận mật khẩu không khớp.',
    registerError: 'Đăng ký thất bại.',
    acceptWith: 'Tôi đã đọc và đồng ý với ',
    terms: 'Điều kiện và điều khoản sử dụng dịch vụ',
  },
  terms: {
    title: 'Điều kiện & điều khoản',
  },
  registerUpdateProfile: {
    title: 'Thông tin cá nhân',
    description:
      'Bạn đã đăng ký tài khoản thành công. Vui lòng cung cấp thông tin cá nhân.',
    addressLabel: 'Địa chỉ',
    addressPlaceholder: 'Nhập địa chỉ của bạn',
    birthdayLabel: 'Ngày sinh',
    birthdayPlaceholder: 'Chọn ngày sinh',
    genderLabel: 'Giới tính',
    genderPlaceholder: 'Chọn giới tính',
    male: 'Nam',
    female: 'Nữ',
    personalBranchLabel: 'Chi nhánh chăm sóc',
    personalBranchPlaceholder: 'Chọn chi nhánh chăm sóc',
    personalStaffLabel: 'Nhân viên chăm sóc',
    personalStaffPlaceholder: 'Nhập tên hoặc mã nhân viên chăm sóc',
    save: 'Lưu thông tin',
    skip: 'Bỏ qua',
    errorMessage: 'Cập nhật thông tin thất bại.',
  },
  unitSelection: {
    title: 'Chọn chi nhánh chăm sóc',
    nearestUnitLabel: 'Chi nhánh gần nhất',
    searchPlaceholder: 'Nhập tên chi nhánh tìm kiếm',
  },
  unitList: {
    nearest: 'Gần nhất',
  },
  bottomTabs: {
    home: 'Trang chủ',
    zone: 'zone',
    other: 'Khác',
  },
  home: {
    topView: 'Xem Nhiều Nhất',
    suggested: 'Gợi Ý Cho Bạn',
    point: 'Điểm ',
    rewardPoint: 'Điểm thưởng',
    newPromotion: 'Ưu đãi mới',
    all: 'Tất cả',
    idPrefix: 'SBD',
    suggestionForYou: 'Đề xuất cho bạn',
    seeDetails: 'Xem chi tiết',
    suffixAnotherBranches: ' cơ sở khác',
    schedule: 'Lịch hẹn sắp tới',
  },
  profile: {
    title: 'Thông tin tài khoản',
    personalInformation: 'Thông Tin Cá Nhân',
    rankInformation: 'Thông tin hạng thành viên',
    pointUsageHistory: 'Lịch sử mua hàng',
    changePassword: 'Đổi mật khẩu',
    setting: 'Cài đặt',
    manageAccount: 'Quản lý tài khoản',
    logout: 'Đăng Xuất',
    personalInformationForm: {
      name: 'Họ Và Tên',
      phoneNumber: 'Số Điện Thoại',
      address: 'Địa Chỉ',
    },
  },
  newsDetails: {
    title: 'Tin Tức',
  },
  pictureOptionsModal: {
    takePhoto: 'Chụp ảnh',
    chooseFromLibrary: 'Ảnh có sẵn',
    cancel: 'Hủy',
  },
  tutorial: {
    description1: 'Đánh thức tâm trí,\nnuông chiều cảm xúc',
    description2: 'Khai mở đa giác quan',
    description3: 'Tái tạo năng lượng khơi gợi xúc cảm',
    description4:
      'Chữa lành từ thiên nhiên, ứng dụng liệu pháp trị liệu cổ truyền',
    description5:
      'Sống khoẻ, sống trọn, tận hưởng hạnh phúc trong từng phút giây',
    register: 'Đăng ký',
    login: 'Đăng nhập',
  },
  verifyOTP: {
    title: 'Nhập mã xác thực',
    description:
      'Mã xác thực đã được gửi tới số điện thoại của bạn. Vui lòng kiểm tra tin nhắn điện thoại để lấy mã xác thực.',
    otpAvailableIn: 'Mã xác thực có hiệu lực trong ',
    verify: 'Xác thực',
    error: 'Mã xác thực không chính xác.',
    otpUnavailable: 'Mã xác thực hết hiệu lực. ',
    resend: 'Gửi lại',
  },
  promotionDetails: {
    title: 'Chi tiết ưu đãi',
    id: 'Mã ưu đãi',
    time: 'Thời gian áp dụng',
    branch: 'Chi nhánh áp dụng',
    rank: 'Hạng thành viên áp dụng',
    customer: 'Khách hàng áp dụng',
    service: 'Dịch vụ áp dụng',
    product: 'Sản phẩm áp dụng',
    details: 'Chi tiết chương trình',
    content: 'Nội dung chính sách chương trình ưu đãi',
    save: 'Lưu ưu đãi',
    usedPrefix: 'Đã dùng ',
    savePromotionSuccessMessage: 'Đã lưu vào Kho ưu đãi.',
    savePromotionFailedMessage: 'Lưu ưu đãi thất bại.',
  },
  changePasswordAfterForget: {
    title: 'Cài đặt mật khẩu',
    description: 'Bạn đã xác thực thành công. Vui lòng nhập mật khẩu mới.',
    newPasswordLabel: 'Mật khẩu mới*',
    newPasswordPlaceholder: 'Nhập mật khẩu mới',
    confirmPasswordLabel: 'Xác nhận mật khẩu*',
    confirmPasswordPlaceholder: 'Nhập lại mật khẩu mới',
    save: 'Lưu mật khẩu',
    confirmPasswordError: 'Xác nhận mật khẩu không khớp.',
    changePasswordSuccessMessage: 'Cài đặt mật khẩu thành công.',
  },
  personalInformation: {
    title: 'Thông tin cá nhân',
    changeTitle: 'Thay đổi thông tin cá nhân',
    fullNameLabel: 'Họ và tên',
    changeFullNameLabel: 'Họ và tên*',
    userIdLabel: 'Mã thành viên',
    phoneNumberLabel: 'Số điện thoại',
    emailLabel: 'Email',
    changeEmailLabel: 'Email*',
    technicianIdPrefix: 'NVS',
    changeInformation: 'Thay đổi thông tin',
    save: 'Lưu',
    successMessage: 'Thay đổi thông tin cá nhân thành công.',
  },
  changePassword: {
    title: 'Đổi mật khẩu',
    oldPasswordLabel: 'Mật khẩu cũ*',
    oldPasswordPlaceholder: 'Nhập mật khẩu cũ',
    successMessage: 'Đổi mật khẩu thành công.',
  },
  developingFeature: {
    title: 'Tính năng đang phát triển.',
  },
  manageAccount: {
    title: 'Quản lý tài khoản',
    closeAccount: 'Đóng tài khoản',
    closeAccountQuestion: 'Bạn có chắc chắn đóng tài khoản không?',
    refuse: 'Từ chối',
    accept: 'Đồng ý',
    closeAccountSuccessMessage: 'Đóng tài khoản thành công.',
    closeAccountFailedMessage: 'Đóng tài khoản thất bại.',
  },
  qr: {
    title: 'Mã QR',
    myQR: 'Mã QR của tôi',
  },
};

export default ja;
